openapi: 3.0.3
info:
  title: Greeting API
  version: 1.0.0
  description: A simple API for greetings and user management

paths:
  /hello:
    get:
      summary: Get a greeting message
      operationId: getGreeting
      tags:
        - greeting
      parameters:
        - name: name
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Successful greeting response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Greeting"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /users:
    post:
      summary: Create a new user
      operationId: createUser
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRequest"
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Greeting:
      type: object
      properties:
        message:
          type: string
          example: "Hello, World!"
        timestamp:
          type: string
          format: date-time

    UserRequest:
      type: object
      required:
        - email
        - name
      properties:
        email:
          type: string
          format: email
        name:
          type: string
          minLength: 2
        preferences:
          type: object
          additionalProperties: true

    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        name:
          type: string
        preferences:
          type: object
          additionalProperties: true
        createdAt:
          type: string
          format: date-time

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
