openapi: 3.0.3
info:
  title: Currency Conversion API
  version: 1.0.0
  description: API for currency conversion

paths:
  /conversion:
    get:
      summary: Convert amount between currencies
      operationId: convertCurrency
      tags:
        - conversion
      parameters:
        - name: sourceCurrency
          in: query
          required: true
          description: ISO 4217 currency code for the source currency
          schema:
            type: string
            minLength: 3
            maxLength: 3
            pattern: "^[A-Z]{3}$"
            example: "USD"
        - name: targetCurrency
          in: query
          required: true
          description: ISO 4217 currency code for the target currency
          schema:
            type: string
            minLength: 3
            maxLength: 3
            pattern: "^[A-Z]{3}$"
            example: "EUR"
        - name: amount
          in: query
          required: true
          description: Amount to convert in the source currency (must be positive)
          schema:
            type: string
            pattern: "^[0-9]+(.[0-9]{1,2})?$"
            example: "100.50"
      responses:
        "200":
          description: Successful conversion
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConversionResponse"
        "400":
          description: Invalid input or unsupported currency
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"
        "429":
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Something unknown went wrong
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "503":
          description: External exchange rate service unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /currencies:
    get:
      summary: Get supported currencies
      operationId: getSupportedCurrencies
      tags:
        - currencies
      responses:
        "200":
          description: List of supported currency codes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  minLength: 3
                  maxLength: 3
                  pattern: "^[A-Z]{3}$"
                  nullable: false
                example: [ "USD", "EUR", "GBP", "JPY" ]
        "500":
          description: Something unknown went wrong
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
          nullable: false
        message:
          type: string
          nullable: false
      required:
        - fields
        - message

    ValidationError:
      type: object
      properties:
        fields:
          type: array
          items:
            type: string
            nullable: false
        message:
          type: string
      required:
        - fields
        - message

    ConversionResponse:
      type: object
      required:
        - convertedAmount
        - date
      properties:
        convertedAmount:
          type: string
          format: decimal
          example: "91.25"
          nullable: false
          description: The converted amount in the target currency
        date:
          type: string
          format: date
          description: The date when the conversion rate was valid
          nullable: false
          example: "2024-02-20"
