services:
  wiremock:
    image: wiremock/wiremock:3.12.0
    ports:
      - "8099:8080"
    volumes:
      - ./wiremock:/home/wiremock
    command:
      - --global-response-templating
      - --verbose
